name: convert.c yml Utility

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build convert
        run: gcc -o convert convert.c convert2.c  
      - name: Upload convert binary
        uses: actions/upload-artifact@v4
        with:
          name: convert
          path: ./convert

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Compile and run testresults
        run: |
          gcc -o convert --coverage convert.c convert2.c
          ./convert
          chmod +x ./test_script
          ./test_script > test_results.txt
          gcov convert-convert.c
          gcov convert-convert2.c
      - name: Upload testresults and show the coverage
        uses: actions/upload-artifact@v4
        with:
          name: test_artifacts
          path: |
            test_results.txt
            *.gcov
            *.gcda
            *.gcno
